name: Continuous Integration - Operacao

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Executar Testes Unitarios
      run: python -m unittest test_missao.py

  alerta:
    name: Disparar Alerta
    runs-on: ubuntu-latest
    needs: testes
    if: failure() # Só roda se os testes falharem e a missão der ruim
    permissions:
      issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Criar Alerta de Falha
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh issue create --title "🚨 ALERTA: Falha na Missão CI/CD" --body "Atenção Ghost, os testes unitários falharam. O código não foi aprovado."
